### ISSUE TITLE
Пожалуйста, опубликуйте пакет в NPM

### ISSUE THREAD

**Issue by huston007** [TinkoffCreditSystems/invest-openapi-js-sdk#1]
На текущий момент пакет не доступен в NPM:
404 по адресу https://www.npmjs.com/package/invest-openapi-js-sdk

**Comment by ZigGreen** [comment]
В ближайшее время опубликуем.

**Comment by ZigGreen** [comment]
Готово. `@tinkoff/invest-openapi-js-sdk`

**Comment by huston007** [comment]
Спасибо!
