### ISSUE TITLE
Расчет валютной переоценки

### ISSUE THREAD

**Issue by andykov** [TinkoffCreditSystems/invest-openapi-js-sdk#103]
Здравствуйте!

Нужно рассчитать старые операции по USD.
Я правильно понимаю, нужно к дате сделки прибавлять 2 торговых дня исходя из режима торгов T+2?
Например:
- Покупка 2020-12-01 + 2д, расчет поручения происходит 3 числа
- Продажа 2020-12-02 + 2д, расчет поручения происходит 5 числа

И какой USD курс ЦБ брать для расчета?
- на конец дня даты расчета поручения? 
- на конец дня совершения сделки?

Спасибо!

**Comment by ZigGreen** [comment]
Привет. С такими вопросами лучше обращаться в поддержку тинькофф инвестиции.
