### ISSUE TITLE
Потеря соединения

### ISSUE THREAD

**Issue by afbagautdinov** [TinkoffCreditSystems/invest-openapi-js-sdk#11]
1) Добавить событие или вызов метода при разрыве соккет соединения.
2) Делать автоматический реконнект соккет соединения при разрыве интернет соединения

**Comment by ZigGreen** [comment]
Привет. Буду благодарен, если будет пр, идея с реконнектом мне нравится больше.

**Comment by BusinessDuck** [comment]
Стало лучше с приходом реконнекта, но все ещё не ясно почему при наличии ответов на пинги от сервера соединение рвётся. Если сетевой протокол написан нормально или это базовый веб сокет, сервер должен понимать что клиент ответил на пинг. Можно ещё с клиента слать пинг серверу, но это оверхед и уже не по стандарту. Скорее всего где то бага. Возможно и на сервере

**Comment by NikitaMelnikov** [comment]
Summon @necryin

**Comment by necryin** [comment]
@BusinessDuck Приветствую. Сетевой протокол написан «нормально» ) Такое может происходить и уже происходило при «некачественном» провайдере. У вас есть возможность проверить на другом провайдере? Так же сервер принудительно разрывает соединение если перегружена очередь отправки, такое возможно при большом количестве подписок на один коннект и/или недостаточной скорости обработки сообщений на клиенте, если обработка синхронная

**Comment by BusinessDuck** [comment]
Хм..., да, похоже ты прав @necryin. Hetzner хостинг сейчас, и действительно почему-то рвет коннект, а вот ростелеком домашний - нет. Какой хостинг лучше взять чтобы пинг был минимальный?

**Comment by necryin** [comment]
Сервера стримов в Москве, так что лучше какой-нибудь хостинг с серверами в Москве)
