### ISSUE TITLE
Не возвращает баланс по CHF

### ISSUE THREAD

**Issue by denisgorev** [TinkoffCreditSystems/invest-openapi-js-sdk#111]
При вызове функции api.portfolioCurrencies() не возвращается информации по швейцарскому франку

![image](https://user-images.githubusercontent.com/45132206/113474781-b8116200-947a-11eb-9cce-667414e9ad54.png)

![image](https://user-images.githubusercontent.com/45132206/113474767-a5972880-947a-11eb-923b-44e690378757.png)

Швейцарский франк на балансе есть

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, на данный момент в openAPI поддерживается только три валюты

**Comment by denisgorev** [comment]
![image](https://user-images.githubusercontent.com/45132206/113509398-021f4400-955e-11eb-8492-469193847760.png)

В спецификации швейцарский франк указан в том числе
