### ISSUE TITLE
Node процесс не завершается

### ISSUE THREAD

**Issue by radzserg** [TinkoffCreditSystems/invest-openapi-js-sdk#112]
Вот пример кода, подобный тому что есть в оф докуументации

```
!(async function run() {
  await api.sandboxClear();
  const marketInstrument = await api.searchOne({ ticker: 'AAPL' }) as MarketInstrument;
  const { figi } = marketInstrument;

  const unsubOrderbook = api.orderbook({ figi }, (ob) => { console.log(ob.bids) });
  unsubOrderbook();
})();
```

`unsubOrderbook` отменит подписку, но Node process повиснит после вызова `api.orderbook`. И не выйдет без принудиттельного `process.exit()` 

Происходит как в песочнице так и на проде.

**Comment by ZigGreen** [comment]
Привет.
Да, соединение открытым остается. Надо делать terminate, если подписок не осталось. 
Можешь закинуть пр?

**Comment by radzserg** [comment]
@ZigGreen  Сделал на коленках, но вроде все работает.
https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/pull/115

**Comment by ZigGreen** [comment]
Спасибо! 
опубликовал v1.2.19
