### ISSUE TITLE
Стриминг падает на событии error без уведомления того что случилось.

### ISSUE THREAD

**Issue by betslus1** [TinkoffCreditSystems/invest-openapi-js-sdk#117]
В документации стриминга есть event "error"
{
    "event": "error",
    "time": "2019-08-07T15:35:00.029721253Z",
    "payload": {
        "request_id": "123ASD1123",
        "error": "Subscription instrument_info:subscribe. FIGI NOOOOOOO not found"
    }
}

в SDK нет обработки этого event и не отправляется причина ошибки роботу
    /**
     * Получение имени ивента
     */
    getEventName(type, params) {
        if (type === 'orderbook') {
            return `${type}-${params.figi}-${params.depth}`;
        }
        if (type === 'candle') {
            return `${type}-${params.figi}-${params.interval}`;
        }
        if (type === 'instrument_info') {
            return `${type}-${params.figi}`;
        }
        throw new Error(`Unknown type: ${type}`);
    }

**Comment by ZigGreen** [comment]
Привет! Можешь послать пулреквест?

**Comment by betslus1** [comment]
Привет,
там репозитарий в typeScript, я его не умею... Да PR не делал никогда.

**Comment by ZigGreen** [comment]
Добавил метод для обработки ошибки `onStreamingError`
версия 1.3.0
