### ISSUE TITLE
Как рассчитывается объем?

### ISSUE THREAD

**Issue by dev-blinov** [TinkoffCreditSystems/invest-openapi-js-sdk#128]
Подписываюсь на данные по свече. 
Указываю: 
**figi**: BBG000DH7JK6
**interval**: 'day'. 

В коллбэке приходят данные, включая объем. Не понятно как он рассчитывается, потому что он ни как не сходится с реальными данными?

**Comment by dev-blinov** [comment]
![image](https://user-images.githubusercontent.com/1014551/125501988-ea27e8dc-c118-43c3-bea8-8392e682067b.png)
![image](https://user-images.githubusercontent.com/1014551/125502015-23eff56b-a677-42b9-bfe0-aa3b4d7f61da.png)

Объемы в Tinkoff и TradingView не совпадают(

**Comment by mlshvdv** [comment]
И не будут. На TradingView вы смотрите график торгов бумаги на **Nasdaq**, соответственно и все данные по торгам: цена и объем соответствуют торгам на этой бирже. В Тиньке бумага торгуется на СПб Бирже, соответственно, данные по торгам будут различаться в виду того, что часть заявок исполняются во внутреннем пуле ликвидности СПб Биржи, а часть во внешнем.

Но, служба поддержки TradingView сообщала в этом году, что работы в сторону интеграции потока данных СПб Биржи ведутся, но там затык именно со стороны биржи.

**Comment by dev-blinov** [comment]
Если я правильно понял, это объемы именно СПБ биржи?

**Comment by mlshvdv** [comment]
Это объемы обобщенные из двух пулов ликвидности: внутреннего (СПб Биржа) и внешнего (США). 

Подробнее тут внизу страницы: https://tinkoffcreditsystems.github.io/invest-openapi/orders/
