### ISSUE TITLE
Invalid json response body

### ISSUE THREAD

**Issue by proairat** [TinkoffCreditSystems/invest-openapi-js-sdk#13]
Хочу считать по месяцам начиная, с 2010 года, дневные свечи, например, по тикеру GAZP. Заметил следующую особенность: каждый последующий запуск скрипта позволяет считать безошибочно меньшее количество данных, нежели предыдущий запуск скрипта. Допустим, я запустил скрипт только что, это приведёт к считыванию всех данных. Затем, если через некоторое время, допустим, спустя 5-10 секунд ещё раз запустить этот же скрипт (второй запуск) с неизменными с предыдущего раза данными, уже вывалится ошибка, представленная на скришоте ниже. Затем если через пару секунд запустить скрипт с неизменными данными с предыдущего раза (третий запуск), то скрипт вывалит ошибку в консоль почти сразу.  Если подождать, допустим, около 1 минуты, то снова повторяется ситуация, а именно начинает считываться без ошибок. Количество раз запуска скрипта всегда разное, но неизменно то, что каждый последующий запуск одних и тех же данных может привести к ошибке, нельзя запустить цикл и быть уверенным в том, что будут прочитаны дневные свечи каждого дня каждого месяца 2010 года. Цикл по годам организовать не выходит, ввиду присутствующей ошибки.

Речь идёт о методе api.candlesGet();

У вас какая-то защита со стороны сервера стоит, учитывающая количество одновременных запросов с одного IP-адреса? Со стороны API в чём может быть дело?

Если опираться на предыдущее описание, то на скриншоте приведён второй запуск скрипта.

![image](https://user-images.githubusercontent.com/48524499/73946429-bbad6580-4917-11ea-9fe6-9224d92cbc1f.png)

**Comment by NikitaMelnikov** [comment]
Добрый день,

Ограничение на количество запросов: https://tinkoffcreditsystems.github.io/invest-openapi/rest/#_1

**Comment by mr-amirka** [comment]
У меня тоже эта ошибка вываливается периодически, несмотря на явное соблюдение ограничений по времени.
Обхожу ошибку, просто повторным вызовом метода по таймауту.
Терпимо, но тем не менее, сама проблема от этого не исчезает.
