### ISSUE TITLE
FetchError: request

### ISSUE THREAD

**Issue by proairat** [TinkoffCreditSystems/invest-openapi-js-sdk#130]
Наблюдаются подобные ошибки сегодня с 10:00 по МСК.

![image](https://user-images.githubusercontent.com/48524499/127979815-252f222e-b9b8-4266-9e42-c8299d06df8e.png)
![image](https://user-images.githubusercontent.com/48524499/127978195-ae5d9860-34e3-42aa-84b0-e850cde534a7.png)

Появляется перед запросами 
await api.instrumentPortfolio()
await api.orders()

В некоторых случаях эти запросы выполняются, но почти всегда возвращается ошибка.
Уже более нескольких месяцев на участке кода, который использует эти функции не было проблем. Наблюдаю эти ошибки сегодня.

Добавилась к предыдущим ошибкам в запросе, ошибка, связанная с await api.searchOne():
![image](https://user-images.githubusercontent.com/48524499/127981795-dd5acc68-d3f7-44ed-ad2c-f9ecf4487374.png)

**Comment by proairat** [comment]
В веб-терминале в виджете "Инструменты" такая ошибка:
![image](https://user-images.githubusercontent.com/48524499/127981977-27b7b2a4-9ee4-47d2-93e9-cd33cda24f1b.png)
Может это связано с предыдущими ошибками с запросами.

**Comment by ZigGreen** [comment]
Привет. Актуальна проблема?

**Comment by proairat** [comment]
Уже не актуальна.
