### ISSUE TITLE
Ошибка в API

### ISSUE THREAD

**Issue by VinokurovDmitriy** [TinkoffCreditSystems/invest-openapi-js-sdk#133]
При любом обращении к API через await возникает ошибка url__WEBPACK_IMPORTED_MODULE_1__.URLSearchParams is not a constructor
Например в примере из документации при даже при очистке песочницы await api.sandboxClear(); в браузере появляется ошибка Unhandled Rejection (TypeError): url__WEBPACK_IMPORTED_MODULE_1__.URLSearchParams is not a constructor

**Comment by ZigGreen** [comment]
Это клиент для Node.js, не для браузера.
