### ISSUE TITLE
Не возвращаются часовые свечи с 2010 по 2018 год

### ISSUE THREAD

**Issue by proairat** [TinkoffCreditSystems/invest-openapi-js-sdk#14]
Здравствуйте. 

Пробовал посредством метода api.candlesGet() вернуть по тикеру GAZP часовые свечи. Проверял следующим образом: брал январь и ноябрь и в каждом из этих месяцев брал диапазон дней с 10 по 16. Ни одна часовая свеча не возвратилась.

Нельзя получить с 2010 года по 2018 год часовые свечи с 10 по 16 января. 
Нельзя получить с 2010 года по 2017 год часовые свечи с 10 по 16 ноября. 
Часовые свечи с 10 по 16 ноября в 2018 году получить можно. 
Часовые свечи с 10 по 16 января в 2019 году получить можно.

Вопрос: почему нельзя получить свечи по тикеру GAZP с 2010 по 2017 годы в январе и ноябре с 10 по 16 числа этих месяцев?

**Comment by timofeigladkikh** [comment]
проблема не в sdk 
свечи с таймфреймом меньше дня есть только после мая 2018
