### ISSUE TITLE
Какие методы в api предназначены для маржинальной торговли?

### ISSUE THREAD

**Issue by proairat** [TinkoffCreditSystems/invest-openapi-js-sdk#16]
Здравствуйте. 
Не нашёл в документации методы для маржинальной торговли. Как использовать возможность торговли с плечом посредством вашего api?

**Comment by ZigGreen** [comment]
На данный момент можно только выставлять заявки, получать информацию по ликвидности нельзя.

**Comment by proairat** [comment]
Я не понял, причём здесь ликвидность и маржинальная торговля? Я в терминале Тинкофф инвестиции мог включить опцию "Маржинальная торговля" и торговать в шорт или торговать в лонг с плечом. Как мне, используя методы вашего api, сделать это? 
![image](https://user-images.githubusercontent.com/48524499/74668369-e83e6880-51c6-11ea-99e0-bdea060ea695.png)

**Comment by ProgrammingLife** [comment]
@ZigGreen, кстати, а будет ли инфа по ликвидности? Раз уж о получении ликвидности речь зашла :)

Ну и по торговле с плечами через OpenAPI тоже интересно.

**Comment by ZigGreen** [comment]
> Я не понял, причём здесь ликвидность и маржинальная торговля? Я в терминале Тинкофф инвестиции мог включить опцию "Маржинальная торговля" и торговать в шорт или торговать в лонг с плечом. Как мне, используя методы вашего api, сделать это?
> ![image](https://user-images.githubusercontent.com/48524499/74668369-e83e6880-51c6-11ea-99e0-bdea060ea695.png)

Выставлять заявки с плечем возможность должна быть.

**Comment by ZigGreen** [comment]
> @ZigGreen, кстати, а будет ли инфа по ликвидности? Раз уж о получении ликвидности речь зашла :)
> 
> Ну и по торговле с плечами через OpenAPI тоже интересно.

Это лучше задавать в [репу](https://github.com/TinkoffCreditSystems/invest-openapi) с самими апишками. А не в JS SDK :)
