### ISSUE TITLE
Нужны подробные примеры использования API

### ISSUE THREAD

**Issue by ProgrammingLife** [TinkoffCreditSystems/invest-openapi-js-sdk#17]
Чтобы не тратить время на чтение документаций, пустых попыток и прочего - нужны конкретные полные примеры использования методов candlesGet (например) и прочих основных. Как и что необходимо установить для работы с вашим API, чтобы максимально быстро начать, а не собирать по крупицам информацию как работать с вашим брокером.

**Comment by vvarh** [comment]
"Чтобы не тратить время на чтение документаций" 😀

в папке пример есть целый пример
[пример](https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/example/index.js)
```
// из примера
// Получаем свечи за конкретный промежуток времени.
    await api.candlesGet({
      from: '2019-08-19T18:38:33.131642+03:00',
      to: '2019-08-19T18:48:33.131642+03:00',
      figi,
      interval: '1min',
    }) 
```

краткое описание методов можно найти в собранном проекте
[node_modules/@tinkoff/invest-openapi-js-sdk/build/OpenAPI.d.ts](node_modules/@tinkoff/invest-openapi-js-sdk/build/OpenAPI.d.ts)

**Comment by ProgrammingLife** [comment]
> в папке пример есть целый пример
И как он работает? Что не так с моими датами?

`const { figi } = await api.searchOne({ ticker: "SBER" });
	try {
		console.log(
			await api.candlesGet({

				// Error: {"message":"[to]: Bad candle interval: from=2020-03-10T15:39:00Z to=2020-03-17T15:46:00Z expected from 1 minute to 1 day","code":"VALIDATION_ERROR"}
				from: "2020-03-10T18:38:33.131642+03:00",
				to: "2020-03-17T18:45:33.131642+03:00",

				//Error: {"message":"[to]: Bad candle interval: from=2020-03-15T13:00:00Z to=2020-03-18T13:00:00Z expected from 1 minute to 1 day","code":"VALIDATION_ERROR"}
				//from: "2020-03-15T13:00:00.000Z",
				//to: "2020-03-18T13:00:00.000Z",
				figi,
				interval: "1min",
			})
		);
	} catch (e) {
		console.log(`Error: ${JSON.stringify(e)}`);
	}`

**Comment by ProgrammingLife** [comment]
Какой максимальный диапазон времени можно выбирать для 1-минутного интвервала, 5, 15, часовок, дневных? Не нашёл этой информации.

**Comment by ProgrammingLife** [comment]
> краткое описание методов можно найти в собранном проекте
> node_modules/@tinkoff/invest-openapi-js-sdk/build/OpenAPI.d.ts
"Not Found"

**Comment by NikitaMelnikov** [comment]
@ProgrammingLife https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles
<img width="753" alt="Снимок экрана 2020-03-19 в 15 09 36" src="https://user-images.githubusercontent.com/1418845/77144462-041f7d80-6a97-11ea-9f53-04a5ec950802.png">

**Comment by NikitaMelnikov** [comment]
@ProgrammingLife https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles

<img width="755" alt="Снимок экрана 2020-03-20 в 10 38 35" src="https://user-images.githubusercontent.com/1418845/77144488-15688a00-6a97-11ea-892b-62a3eb2ed28e.png">
