### ISSUE TITLE
api.candle

### ISSUE THREAD

**Issue by koshik34** [TinkoffCreditSystems/invest-openapi-js-sdk#19]
Есть какие то ограничения по количеству или подписка ограниченна по времени?
Столкнулся с странной ситуацией:
  Подписался на тикер.
  callback отрабатывает при смене данных.
  Через 20(+/-) минут перестает срабатывать callback на изменение данных тикера.

**Comment by ZigGreen** [comment]
возможно связано с #11

**Comment by BusinessDuck** [comment]
Связано с 11 , происходит разрыв соединения с сервером, тк нет ответа на пинг. И если нет никаких исходящих команд, соединение закрывается.

**Comment by ZigGreen** [comment]
Будет решено с #11
