### ISSUE TITLE
Улучшить автогенерируемые типы

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi-js-sdk#21]
Текущий авогенерируемый файл d.ts с типами, это просто декларации. Они, по идее, для импорта не предназначены, тоесть нельзя сделать import что-то from './domain.d.ts'; без магии. В такой конструкции d.ts на самом деле будет работать как .ts файл. Нормальная логика работы тайпскрипта это иморт файла, а заметем поиск декларация для него. 
Например импортируем файл domain.ts -> тайпскрипт проверит, нет ли файла domain.d.ts чтобы получить декларации. По отдельности d.ts обычно не используют в не скомпилированных проектах.

Также стоит добавить префикс в автосгенерированный файл 
/** Файл генерируется автоматически */ 

Так хотябы будет понятно людям которые работают с SDK что при PR не трогать этот файл

**Comment by ZigGreen** [comment]
+ нужно написать скрипты в package.json для билда типов и перегенерации доки.
