### ISSUE TITLE
Правильный экспорт типов

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi-js-sdk#22]
Пишу проект на тайпскрипте, не хватает базовых типов, они просто не экспортируются из sdk

**Comment by ZigGreen** [comment]
В версии 1.2.5 должно быть норм. Проверь пожалуйста.

**Comment by BusinessDuck** [comment]
Да, шикарно мы проапдейтили сдк, теперь все четко. Я, довольный клиент ;)
