### ISSUE TITLE
Не хватает цены в типе

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi-js-sdk#23]
Я размещаю заявку, в ответе нет цены размещения. Приходится хранить цену отдельно от заявки.

```typescript
export declare type PlacedLimitOrder = {
    orderId: string;
    operation: OperationType;
    status: OrderStatus;
    rejectReason?: string;
    message?: string;
    requestedLots: number;
    executedLots: number;
    commission?: MoneyAmount;
};
`

**Comment by ZigGreen** [comment]
@NikitaMelnikov может есть смысл от апи возвращать?

**Comment by BusinessDuck** [comment]
Также странно, что bid и ask, цены, нигде не фигурируют. Тоесть я не знаю какой примерно у инструмента спред. Ожидал что MarketInstrument долежн в себе иметь spread
```typescript

export type SearchMarketInstrument = {
    figi: string;
    ticker: string;
    isin?: string;
    minPriceIncrement?: number;
    lot: number;
    currency?: Currency;
    name: string;
    type: InstrumentType;
};
```

**Comment by NikitaMelnikov** [comment]
bid, ask и другие фигурируют в /market/orderbook и в подписках

Методы search предоставляют только базовую информацию

**Comment by ZigGreen** [comment]
@NikitaMelnikov а что с PlacedLimitOrder?

**Comment by BusinessDuck** [comment]
Призываю @NikitaMelnikov . Добавьте цену в limit заявку

**Comment by NikitaMelnikov** [comment]
Цену вы отправляете при выставлении поручения, нужно ли ее дублировать в ответе? Для какого случая?

**Comment by BusinessDuck** [comment]
Лимит заявка по цене не ниже чем(из документации) значит не факт что все сделки в ней будут по указаной цене

**Comment by NikitaMelnikov** [comment]
При создании заявки там не может быть цены исполнения, так как она исполняется не сразу

**Comment by BusinessDuck** [comment]
> При создании заявки там не может быть цены исполнения, так как она исполняется не сразу

речь шла про цену рамещения,  тк допустим при переразмещении цену у других брокеров можно редактировать. Тем самым реализуя маркет трейлинг сделок

**Comment by BusinessDuck** [comment]
@NikitaMelnikov по той же причине в ордере есть take и stop цены, сейчас тейки и стопы реализуются через маркет ордера, это тоже проблемно, утраивает кол-во запросов. При работе с биржей на каждом запросе можно сфейлиться (попасть на ошибку и войти в неконсистентное состояние - да разработчик сам дурак) и потерять деньги. Я думаю, что критически важно сводить их к минимуму.

**Comment by NikitaMelnikov** [comment]
@BusinessDuck в данный момент есть технические ограничения, которые не дают физически редактировать заявку, но я с вами согласен, что лимитов запросов может не хватить.
