### ISSUE TITLE
Неправильно генерируются типы

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi-js-sdk#25]
Вот отсюда и ниже несколько типов генерируются не правильно.
https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/src/domain.ts#L221

**Comment by ZigGreen** [comment]
relates: https://github.com/TinkoffCreditSystems/swagger-types-generator/issues/2

**Comment by ZigGreen** [comment]
fixed @tinkoff/invest-openapi-js-sdk@1.2.5
