### ISSUE TITLE
ReferenceError: URLSearchParams is not defined

### ISSUE THREAD

**Issue by koshik34** [TinkoffCreditSystems/invest-openapi-js-sdk#28]
api.searchOne({
    ticker: 'WDC',
  })

**Comment by BusinessDuck** [comment]
В браузере или в ноде случается? 
node -v что покажет?

**Comment by koshik34** [comment]
В ноде.
node -v
v9.11.2

**Comment by ZigGreen** [comment]
В браузере вообще не будет работать пока что.

**Comment by BusinessDuck** [comment]
`

import { URLSearchParams } from 'url';
global.URLSearchParams = URLSearchParams

`

**Comment by ZigGreen** [comment]
Можешь немного подробнее пояснить?

**Comment by BusinessDuck** [comment]
Да, с 10 версии ноды этот объект доступен глобально, для более старых его нужно импортировать. Так что добавление импорта просто, уже решит проблему. (Можно только первую строку добавить из моего коммента выше)

**Comment by ZigGreen** [comment]
Так правки в либу никакие вносить не нужно получается. Просто поставить ноду 10

**Comment by BusinessDuck** [comment]
У тебя есть два пути, поднять минимальную версию ноды до 10 в package json файле отметить это. Или добавить импорт. Решать тебе.
