### ISSUE TITLE
Разделение ws и xhr

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi-js-sdk#29]
1) Необходимо разделить SDK на socket и xhr составляющие. Тк socketURL как входной параметр не нужен для работы REST ровно как и RESTurl для работы сокет. 
2) Версия SDK жестко привязана к определенной версии API, значит нет смысла задавать ссылку на API как входной параметр, тк в документации при обновлении будет меняться ссылка (если вышли новые API) и вряд ли клиент обновит ссылки у себя. Поэтому резонно сделать входной контракт : new OpenAPI({ sandbox: boolean; token: string }); и уже под капотом выставлять ссылку на песочницу или в прод, тк вряд ли старая версия библиотки будет работать с новым апи и наоборот.

**Comment by ZigGreen** [comment]
ок, со вторым согласен. А зачем разделять сокеты и рест? Как будет выглядеть публичный интерфейс тогда у сдк?

**Comment by BusinessDuck** [comment]
возможно получится вообще избавиться от конструктора для вызова POST/GET методов апи, конструктор не очень удобен в это плане, хотя может если он упростится то не придется везде прокидывать ссылку на сокет и апи и станет удобнее.

**Comment by BusinessDuck** [comment]
@ZigGreen Добавь параметр и закрывайте, стрим разделен уже в https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/pull/42
