### ISSUE TITLE
MarketInstrument missed name property

### ISSUE THREAD

**Issue by nkt** [TinkoffCreditSystems/invest-openapi-js-sdk#3]
Please add `name: string` to https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/src/domain.d.ts#L164 
Docs: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_search_by_figi

**Comment by ZigGreen** [comment]
1e34302dcb16a282cc6fb50a4ec790cd85463f93 closes this issue 

1.0.8 version published as well

**Comment by nkt** [comment]
👍
