### ISSUE TITLE
Не могу установить RUB в sandbox

### ISSUE THREAD

**Issue by koshik34** [TinkoffCreditSystems/invest-openapi-js-sdk#31]
```
await api.setCurrenciesBalance({ currency: 'RUB', balance: 1000 });
await api.portfolio(); 
```
Вывод:
```
{ positions: [] }
```
Если сменить RUB на USD.
Вывод:
```
{
  positions: [
    {
      figi: 'BBG0013HGFT4',
      ticker: 'USD000UTSTOM',
      instrumentType: 'Currency',
      balance: 1000,
      blocked: 0,
      lots: 1,
      name: 'Доллар США'
    }
  ]
}
```

**Comment by ProgrammingLife** [comment]
Видимо, в более старых версиях нет такой траблы. У меня оно работает для RUB, но версия месяца на 2 устарела.

**Comment by ZigGreen** [comment]
Устанавливается, просто используйте [portfolioCurrencies](https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/doc/classes/openapi.md#portfoliocurrencies) для получения позиций по валютам.
