### ISSUE TITLE
Неверный формат поля 'interval' в запросе

### ISSUE THREAD

**Issue by mr-amirka** [TinkoffCreditSystems/invest-openapi-js-sdk#32]
В методе api.candlesGet для параметра "interval" не работают опции перечисленные в документации: "2hour" | "4hour"
Ошибка:
```
{
  message: "Неверный формат поля 'interval' в запросе",
  code: 'MALFORMED_QUERY_PARAMETER'
}
```

**Comment by ZigGreen** [comment]
да, есть неточность. 
Верные значения: 1min, 2min, 3min, 5min, 10min, 15min, 30min, hour, day, week, month
