### ISSUE TITLE
TypeError: URLSearchParams is not a constructor

### ISSUE THREAD

**Issue by zovcharov** [TinkoffCreditSystems/invest-openapi-js-sdk#33]
Got this error, trying to run your example, but with `require` instead of `imports`
`node -v` : v8.15.1
That is strange, because this SDK called as nodeJS SDK on the tinkoff web page, but it can`t work with system modules.

```
const URLSearchParams = require('url');
const OpenAPI = require('@tinkoff/invest-openapi-js-sdk');

global.URLSearchParams = URLSearchParams;

const sandboxApiURL = 'https://api-invest.tinkoff.ru/openapi/sandbox/';
const socketURL = 'wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws';
const sandboxToken = '...';
const api = new OpenAPI({ apiURL: sandboxApiURL, secretToken: sandboxToken, socketURL });

!(async function run() {
  await api.sandboxClear();

  const marketInstrument = await api.searchOne({ ticker: 'AAPL' });
  const { figi } = marketInstrument;

  console.log(
    await api.candlesGet({
      from: '2019-08-19T18:38:33.131642+03:00',
      to: '2019-08-19T18:48:33.131642+03:00',
      figi,
      interval: '1min',
    })
  );
})();
```

**Comment by koshik34** [comment]
Hi.
I had the same problem. Try updating the node to version 10.

**Comment by zovcharov** [comment]
I`ve already done with this problem by updating. But why is it so? Maybe it will be better to be possible use default modules system for nodeJS.
I don`t think that it`s really difficult.

**Comment by ZigGreen** [comment]
It seems like setting the module to 'CommonJS' would help.

**Comment by ZigGreen** [comment]
Hm 🤔  I've tried to run an example code with node ver you were running (v8.15.1) tho' it went with no errors at all.
I'll close the issue for now. Feel free to reopen it if there are any questions to discuss on the topic.
