### ISSUE TITLE
Как конроллировать выполнение лимитного ордера?

### ISSUE THREAD

**Issue by ProgrammingLife** [TinkoffCreditSystems/invest-openapi-js-sdk#34]
В **api.orders()** будут числиться только незавершённые ордера? Соответственно, как получить информацию по идентификатору ордера (насколько он заполнен), если соединение прервалось и ордер ещё не заполнился?

**Comment by ZigGreen** [comment]
@NikitaMelnikov можешь помочь?

**Comment by betslus** [comment]
Насколько я понимаю, пулять в https://api-invest.tinkoff.ru/openapi/operations по каждой бумажке отдельно. Количество запросов к API в этом случае равно количеству бумаг в работе.
Может сделать или запрос к operations без привязки к figi или websocket подписку на обновления для снижения нагрузки на сервера?

**Comment by ProgrammingLife** [comment]
@betslus В общем гите сдк сказали, что FIGI оказывается необязателен в operations.

**Comment by ZigGreen** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi/issues/172

**Comment by betslus** [comment]
Спасибо! Переделаю!

**Comment by betslus** [comment]
Думаю ошибка в библиотеке.
Если поменять 

>     OpenAPI.prototype.operations = function (_a) {
>         var from = _a.from, to = _a.to, figi = _a.figi;
>         return this.makeRequest('/operations', {
>             params: { from: from, to: to, figi: figi },
>         });
>     };

на 

>     OpenAPI.prototype.operations = function (_a) {
>         var from = _a.from, to = _a.to, figi = _a.figi;
>         return this.makeRequest('/operations', {
>             params: { from: from, to: to},
>         });
>     };


То все ок, вероятно API вообще не должен получать никаких, даже пустых параметров figi, чтобы возвращать все операции.

**Comment by ZigGreen** [comment]
Да, все правильно. Надо внести правки в библиотеку.

**Comment by ZigGreen** [comment]
Fixed @tinkoff/invest-openapi-js-sdk@1.2.8
