### ISSUE TITLE
Правильно ли возвращаются объёмы? Я получаю объёмы в 10 раз меньше

### ISSUE THREAD

**Issue by ProgrammingLife** [TinkoffCreditSystems/invest-openapi-js-sdk#36]
Там где у Сбера объём на минутке: 2801040 (смотрю в Tradingview), то я получаю объём: 280104. Постоянно во всех объёмах куда-то теряется последний ноль и объёмы получаются в 10 раз меньше. В чём может быть проблема?
Использую последний SDK, получение исторических свеч, 1m, Сбер.

**Comment by betslus** [comment]
У сбера один лот = 10 акций.
