### ISSUE TITLE
Обработка ошибок

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi-js-sdk#46]
В 7ом часу утра случилось вот такое.

```bash
(node:21923) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://api-invest.tinkoff.ru/openapi/orders reason: Unexpected token S in JSON at position 0
```

API по какой-то причине ответила не JSON'ом на запрос. Замечал это в любых других вызовах. Например, если слишком часто зправшивать историю и помногу. 

Нужно сделать более "бережный" парсинг JSON овтета, обработать ситуацию, когда ответ 200 но формат не JSON.

Если статус 200 и формат не JSON по идее это косяк самого апи, такого быть не должно, даже все ошибки должны быть обернуты в ожидаемый тип ответа.

**Comment by ZigGreen** [comment]
Выглядит как бага апишки, а не сдк.

**Comment by betslus** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/issues/35
