### ISSUE TITLE
FIGI v.s. Ticker

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi-js-sdk#47]
Кажется что работать с **Ticker** сильно более удобно для потребителя. В тех методах в которых требуется **FIGI**, постоянно вынуждает дернуть дополнительный вызов и его разобрать полувич **FIGI**. Это неудобно!

Расскажите что такое **FIGI** и почему лучше и удобнее работать с ним?
Или может быть стоит спрятать его от пользователей и оставить только **Ticker** ?

**Comment by ZigGreen** [comment]
тикер -- это не id инструмента. Поэтому метод search по ticker возвращает список, а по [figi](https://en.wikipedia.org/wiki/Financial_Instrument_Global_Identifier) возвращает инструмент.
Из-за этого сложно как-то предусмотреть возможность передавать везде тикер.

**Comment by BusinessDuck** [comment]
Я так понимаю что эти id, постоянные? Может сделать локально мини кеш инструментов, в которых сразу манить ticker -> figi, если в кеше нет , дергать поиск. Периодически обновлять кеш с релизами сдк. 
Пирит - Меньше нагрузки на апи, удобнее  для юзеров.

**Comment by ZigGreen** [comment]
дело в том, что тикеры не уникальные. Они уникальны только в рамках одной биржи.

**Comment by BusinessDuck** [comment]
Спасибо.
