### ISSUE TITLE
Разрывы соединений. 

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi-js-sdk#48]
Хостинг в москве. Пинг 1 мс до ваших серверов апи.
Наблюдаю разрывы соединения.

10:07:04 AM  connection closed
10:07:04 AM  connection opened
10:20:20 AM  connection closed
10:20:20 AM  connection opened
10:25:42 AM  connection closed
10:25:42 AM  connection opened
11:45:57 AM  connection closed
11:45:57 AM  connection opened
11:51:44 AM  connection closed
11:51:44 AM  connection opened
11:57:12 AM  connection closed
11:57:12 AM  connection opened

**Comment by BusinessDuck** [comment]
Подключается в ту же секунду, проблем с сетью нет. Что-то не так с механизмом keep-alive

**Comment by ZigGreen** [comment]
надо бы этот ишью перенести в основную репу openapi

**Comment by BusinessDuck** [comment]
pr fix https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/pull/50#pullrequestreview-402581834

**Comment by berzhok** [comment]
Ребят есть прогресс? а то уже действительно достали разрывы...

**Comment by ZigGreen** [comment]
@berzhok проверь в @tinkoff/invest-openapi-js-sdk@1.2.11
