### ISSUE TITLE
 Подписка orderbook, тип OrderbookStreaming

### ISSUE THREAD

**Issue by AlShu** [TinkoffCreditSystems/invest-openapi-js-sdk#49]
Почему в OrderbookStreaming типе
есть 'bids', но нету 'asks' ?

**Comment by AlShu** [comment]
я же правильно понимаю что в функцию
orderbook  передается callback  который будет дергаться каждый раз когда пришли новые данные из стрима? если да- то текущая реализация в корне отличается от описанной тут:
https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/

И еще во всех ответах и ивентах от сервера оч нужно возвращать время, в текущем типе его нет, хотя по ссылке выше предпологается.

**Comment by ZigGreen** [comment]
там скорее всего тип неправильный. А так данные приходить должны.

**Comment by ZigGreen** [comment]
Добавлен тип в @tinkoff/invest-openapi-js-sdk@1.2.12
