### ISSUE TITLE
./build/OpenAPI not found

### ISSUE THREAD

**Issue by tamazyanarsen** [TinkoffCreditSystems/invest-openapi-js-sdk#5]
https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/300808a4919e4df80205f33e77ccd8b8396047e0/index.d.ts#L1
Hello!
Where is ./build ?

**Comment by ZigGreen** [comment]
Hello!
It's an auto-generated file. 
To get it going run `npm i & npm run build`

**Comment by tamazyanarsen** [comment]
> Hello!
> It's an auto-generated file.
> To get it going run `npm i & npm run build`

Thanks, it helped
