### ISSUE TITLE
Market order

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi-js-sdk#51]
Нет поддержки заявки по рынку.

**Comment by proairat** [comment]
В документации описан метод выставления рыночной заявки. В версии @tinkoff/invest-openapi-js-sdk@^1.2.6 этот метод отсутствует в исходных файлах. Я взял за пример метод лимитной заявки и включил его в свой исходный файл:

OpenAPI.prototype.marketOrder = function (_a) {
        var figi = _a.figi, lots = _a.lots, operation = _a.operation, price = _a.price;
        return this.makeRequest("/orders/market-order?figi=" + figi, {
            method: 'post',
            params: {
                lots: lots,
                operation: operation,
            },
        });
    };

**Comment by proairat** [comment]
Из программного кода метод вызываю следующим образом:
let market_order = await api.marketOrder({
            figi,
            operation,
            lots
        });

**Comment by proairat** [comment]
От себя добавлю, что документация и примеры настолько скудные, что приходится разбираться во всём методом проб и ошибок.

**Comment by ZigGreen** [comment]
привет! Круто, если кто-то сделает пр по аналогии с лимитной заявкой.

**Comment by ZigGreen** [comment]
> От себя добавлю, что документация и примеры настолько скудные, что приходиться разбираться во всём методом проб и ошибок.

А какой инфы нет в [документации](https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/doc/classes/openapi.md)?

**Comment by ZigGreen** [comment]
duplicates: #15

**Comment by ZigGreen** [comment]
Добавил в версии  @tinkoff/invest-openapi-js-sdk@1.2.7

**Comment by BusinessDuck** [comment]
Поставил сегодня апдейт, посмотрим как работает. Спасибо!
