### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by aigoncharov** [TinkoffCreditSystems/invest-openapi-js-sdk#53]
Добрый день!
Спасибо за разработу и поддержку этого SDK! Отдельное спасибо за TypeScript!
Под какой лицензией распространяется данный SDK? В данный момент в репозитории нет лицензии. Обычно, это значит, что с [этим кодом вообще ничего нельзя делать](https://choosealicense.com/no-permission/).
В идеале, хотелось бы увидеть этот проект под [MIT](https://en.wikipedia.org/wiki/MIT_License) лицензией.

**Comment by ZigGreen** [comment]
привет! указал лицензию. Apache License 2.0

**Comment by aigoncharov** [comment]
Круто! Спасибо!
