### ISSUE TITLE
Ошибка при запуске примера

### ISSUE THREAD

**Issue by tamazyanarsen** [TinkoffCreditSystems/invest-openapi-js-sdk#6]
![image](https://user-images.githubusercontent.com/25464296/69491901-98445400-0eac-11ea-8485-218b79e2cbcb.png)
запускаю через ts-node <filename>.ts

![image](https://user-images.githubusercontent.com/25464296/69491917-cb86e300-0eac-11ea-9d2e-ef9edfc4b7cd.png)

использовал этот пример 
![image](https://user-images.githubusercontent.com/25464296/69491922-d772a500-0eac-11ea-9e45-65ace904212c.png)

**Comment by ferdibiflator** [comment]
@tamazyanarsen попробуй импортить не дефолт, то есть с фиг скобками 

```
import { OpenAPI } ....
```

**Comment by tamazyanarsen** [comment]
> @tamazyanarsen попробуй импортить не дефолт, то есть с фиг скобками
> 
> ```
> import { OpenAPI } ....
> ```

пробовал, тогда ошибка импорта 
нужно без скобок, потому что там export default

**Comment by ZigGreen** [comment]
Привет!
@tamazyanarsen напиши плз какой командой запускаешь.

**Comment by tamazyanarsen** [comment]
мой tsconfig 
![image](https://user-images.githubusercontent.com/25464296/69565421-fd3f9d00-0fc5-11ea-875a-2e9e233e0bed.png)

запускаю через ts-node

**Comment by ZigGreen** [comment]
Просто укажи еще "esModuleInterop": true,

**Comment by tamazyanarsen** [comment]
> Просто укажи еще "esModuleInterop": true,

👍🏻
