### ISSUE TITLE
Неверный параметр time_in_force для инструмента в рыночной заявке

### ISSUE THREAD

**Issue by proairat** [TinkoffCreditSystems/invest-openapi-js-sdk#62]
Здравствуйте. Сегодня приблизительно в 23:05 по Московскому времени была получена следующая ошибка:

![image](https://user-images.githubusercontent.com/48524499/81740703-d06d3c80-94b6-11ea-9a1d-1ed8fbe5b56f.png)

Применяю метод api.marketOrder();
Тикер "HAL" (Halliburton). Использую @tinkoff "version": "1.2.8".

Метод api.marketOrder() до 23:05 работал исправно, я его использовал и он работал до этого времени.

**Comment by NikitaMelnikov** [comment]
Добрый день, это ошибка биржи, работаем над исправлением
