### ISSUE TITLE
Вопрос по WebSocket

### ISSUE THREAD

**Issue by koshik34** [TinkoffCreditSystems/invest-openapi-js-sdk#63]
Я подписываюсь на изменение цены через ` api.candle `на 42 акции.
Прочитал что 

> "Ограничения
> Доступно 6 tcp-соединений на одного пользователя."

Что это значит для меня?
Что подписка сбрасывается и по итогу я подписываюсь только на последние 6?
Или это вообще про количество запущенных ботов одновременно?

**Comment by BusinessDuck** [comment]
> Я подписываюсь на изменение цены через `api.candle`на 42 акции.
> Прочитал что
> 
> > "Ограничения
> > Доступно 6 tcp-соединений на одного пользователя."
> 
> Что это значит для меня?
> Что подписка сбрасывается и по итогу я подписываюсь только на последние 6?
> Или это вообще про количество запущенных ботов одновременно?

Это про количество одновременных соединений. То есть на каждое новое создание объекта OpenAPI создается новое соединение. Если у вас 42 акции на одном обьекте - то все впорядке. Но если вы используете в разных местах разные OpenAPI то их только 6 можно

**Comment by ZigGreen** [comment]
Да, неплохо бы иметь пример кода, зачем создавать много экземпляров OpenAPI

**Comment by BusinessDuck** [comment]
У меня например каждый бот создает для себя отдельный транспорт, тк запускаю я их через "демонизатор" ака менеджер процессов. 

```bash
pm2 start ./out/bots/surfer/start.js --name=surfer_ADSK -- port=8080 token=prod cfg=ADSK amount=260
pm2 start ./out/bots/3in1-sma/start.js --name=TIO_SIG -- port=8080 token=prod cfg=SIG amount=260
```
таким образом, я могу останавливать и запускать ботов по одному, менять им конфигурацию и не перезапускать всю систему. Все мои боты, повторюсь, создают транспорт себе сами.
Я быстро уперся в лимит 6, и создал прокси сервер к которому подключаются все мои боты, их 50 на данный момент, дальше прокси передает все на сервер ТИ через одно единственное соединение.

Приведите пример архитектуры, где не требовалось бы создавать каждому боту транспорт отдельно и при этом боты были бы микросервисами подключаемыми и отключаемыми?

**Comment by ZigGreen** [comment]
@koshik34 у тебя такая же ситуация? Если да, то @BusinessDuck уже сделал решение с поднятием прокси-сервера. Пока что думаю над тем брать подобное решение или нет.

**Comment by koshik34** [comment]
@ZigGreen Не, у меня все гораздо проще. 
1 бот следит за акциями

**Comment by ZigGreen** [comment]
Если нет вопросов больше, я закрываю ишью. 
you're welcome to reopen it. :)
