### ISSUE TITLE
Как передать данные в приложение?

### ISSUE THREAD

**Issue by zarahov-s** [TinkoffCreditSystems/invest-openapi-js-sdk#68]
Здравствуйте. Подскажите пожалуйста как мне передать данные в vue приложение через сокет подключение?

Опыта с сокетами не имел, поэтому трудности.

Я взял расширенный пример из **example/index.js**
Только поменял метод на подписку
```js
console.log(
  await api.candle({
    figi,
    interval: '1min',
  })
);
```
Все работает, в консоле вижу данные. Но как их отдать приложению чтобы на странице данные обновлялись в режиме реального времени?

Создал локальный сервер на Koa.js и роут, чтобы потом из Vue к нему подключатся:
```js
expRouter.get('/', async (ctx, next) => {
	const marketInstrument = await api.searchOne({ ticker: 'AAPL' });
  	const { figi } = marketInstrument;

	// Тут выдает 500 ошибку **Internal Server Error**
	// ctx.body = await api.candle({
	// 	figi,
	// 	interval: '1min',
	// })

	// Этот вариант возвращает JSON, но это не реалтайм подписка.
	ctx.body = await api.candlesGet({
		from: '2019-08-19T18:38:33.131642+03:00',
		to: '2019-08-19T18:48:33.131642+03:00',
		figi,
		interval: '1min',
	})
});
```

Как я понял нужно из самого клиента подключатся, но это не работает, авторизация по сокету не проходит.

**Comment by ZigGreen** [comment]
Привет!
стриминг методы это
[candle](https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/doc/classes/openapi.md#candle)
[orderbook](https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/doc/classes/openapi.md#orderbook)

Как написано в документации они принимают вторым параметром колбек, куда будут приходить новые данные:
```ts
const { figi } = await api.searchOne({ ticker: 'AAPL' });
const unsubFromAAPL = api.orderbook({ figi }, (ob) => { console.log(ob.bids) });
// ... подписка больше не нужна
unsubFromAAPL();
```

Чтобы клиентское приложение имела доступ, нужно поднять свой сокет сервер и просто проксировать эти данные на клиент.

Если есть репозиторий с примером того, что не работает, то я попытаюсь более предметно дать подсказку.

**Comment by ZigGreen** [comment]
Пока что закрываю пр, если вопросы остались -- feel free to reopen it. :D
