### ISSUE TITLE
Необходимые параметры в функции candle

### ISSUE THREAD

**Issue by tamazyanarsen** [TinkoffCreditSystems/invest-openapi-js-sdk#7]
https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/300808a4919e4df80205f33e77ccd8b8396047e0/src/OpenAPI.ts#L388

в документации (https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles) сказано, что эта функция должна принимать 4 параметра
в коде только 2
как передать еще 2 параметра (from, to)?
![image](https://user-images.githubusercontent.com/25464296/69544299-775d2b00-0fa0-11ea-9cfe-ca3f2d786258.png)

**Comment by ZigGreen** [comment]
Это новый метод, в текущей версии клиента его нет. То, что сейчас есть -- подписка на стрим данных по свечам.

**Comment by ZigGreen** [comment]
Добавил в версии `1.1.0`
https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/doc/classes/openapi.md#candlesget

**Comment by tamazyanarsen** [comment]
> Добавил в версии `1.1.0`
> https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/doc/classes/openapi.md#candlesget

спасибо!
