### ISSUE TITLE
Ошибка при обработке Webpack

### ISSUE THREAD

**Issue by almirus** [TinkoffCreditSystems/invest-openapi-js-sdk#70]
Возникает ошибка, если заюзать модуль invest-openapi-js-sdk через webpack
`Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (OpenAPI.esm.js:6)
    at Module../node_modules/@tinkoff/invest-openapi-js-sdk/build/OpenAPI.esm.js (OpenAPI.esm.js:472)
    at __webpack_require__ (bootstrap:79)`

[Тут](https://github.com/webpack/webpack/issues/4039) написано что из-за одновременного использования конструкций import и export, рекомендуют заменить module.exports syntax на export default

**Comment by ZigGreen** [comment]
Привет. sdk для ноды. Зачем собирать вебпаком?

**Comment by almirus** [comment]
Хотел на клиенте заюзать, для chrome плагина

**Comment by ZigGreen** [comment]
Работоспособность в браузере не тестировалась. + сокет работать точно не будет из-за авторизации.

**Comment by almirus** [comment]
сокетный вариант и нужен был, нашел обходной путь, спасибо за ответы 😉

**Comment by penoplaster83** [comment]
Ловлю ту же ошибку пытаясь запустить проект на **Vue**.

Подскажите, как правильно законфижить. Бьюсь, курю форумы, - не могу понять

**Comment by ZigGreen** [comment]
Библиотека работает только на node.js. Для браузера рекомендую написать свой сервер и взаимодействовать с ним.
