### ISSUE TITLE
candlesGet падает с пустой ошибкой

### ISSUE THREAD

**Issue by kniknak** [TinkoffCreditSystems/invest-openapi-js-sdk#72]
```
                try {
                    const instrumentInfo = await api.candlesGet({
                        from: from.toISOString(),
                        to: (new Date()).toISOString(),
                        figi: tickerInfo[ticker].figi,
                        interval: 'day',
                    });
                } catch(e) {
                    console.log("Error in candlesGet", e)
                }
```
Этот код периодически падает, но в ошибке пустой вывод.

Падает в 50%+ запросов на разных тикерах
Версия open-api: 1.2.3

**Comment by ZigGreen** [comment]
Надо бы добавить логирование запросов\ответов к апи.

А сейчас просто предлагаю подебажить, что отвечает сервер. Вот [сюда можно дебагер](https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/src/OpenAPI.ts#L100) поставить и посмотреть.

**Comment by koshik34** [comment]
Поставь задержку между запросами, мне помогло

**Comment by kniknak** [comment]
@koshik34 Спасибо, задержка помогла

Я так понимаю, что я упирался в лимит запросов.
@ZigGreen Мне кажется, что было бы здорово отлавливать и обрабатывать такие эксепшны

**Comment by BusinessDuck** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/pull/71 это PR исправляет

**Comment by BusinessDuck** [comment]
> @koshik34 Спасибо, задержка помогла
> 
> Я так понимаю, что я упирался в лимит запросов.
> @ZigGreen Мне кажется, что было бы здорово отлавливать и обрабатывать такие эксепшны

Вы можете на клиенте обработать, у меня запрос истории делается батчем по 50 дней (50 запросов по 1 дню), затем следующий чанк, если ошибки загрузки, весь батч грузится заново и тд... не обязательно там знать текст ошибки, главное знать что ошибка есть, а дальше уже просто повторить запрос через какой-то интервал времени
