### ISSUE TITLE
Что за параметры в CandleStreaming?

### ISSUE THREAD

**Issue by DarkTraveler** [TinkoffCreditSystems/invest-openapi-js-sdk#82]
Добрый день, не нашел описание CandleStreaming, возвращаемое, например, api.candle. 

`export declare type CandleStreaming = {  
    o: number;  
    c: number;  
    h: number;  
    l: number;  
    v: number;  
    time: string;  
    interval: Interval;  
    figi: string;  
};`

В примере, предлагают использовать h (Текущее значение), но сразу возникает вопрос, 
что лежит в других параметрах (o, c, l, v)?

`  o: 1849,
  c: 1848.1,
  h: 1850,
  l: 1848,
  v: 663,
  time: '2020-07-31T16:12:00Z',
  interval: '1min',
  figi: 'BBG004PYF2N3'`

**Comment by mlshvdv** [comment]
https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/

**Comment by DarkTraveler** [comment]
@mlshvdv спасибо большое!
