### ISSUE TITLE
Можно ли получить ценность определенной акции в портфеле?

### ISSUE THREAD

**Issue by DarkTraveler** [TinkoffCreditSystems/invest-openapi-js-sdk#84]
Добрый день, как понимаю, нельзя пока получить стоимость определенных акций в портфеле? Только среднее значение. 

В API приходит только среднее по купленным акциям (instrumentPortfolio)
averagePositionPrice: { currency: 'RUB', value: 39.76 },

Скрин с главной страницы тинкофф
![image](https://user-images.githubusercontent.com/16899697/89211459-32949400-d605-11ea-99a0-60687b52b5b2.png)

**Comment by mlshvdv** [comment]
Разве что считать вручную: `averagePositionPrice.value * lots + expectedYield.value`

**Comment by DarkTraveler** [comment]
@mlshvdv Спасибо. Угу, я затупил, первый раз при подсчете, сумма не совпала у всех с тем, что я видел в лк.

Сейчас как раз перепроверил. Возможно, где-то есть задержка, или в лк при обновление, или в API.

**Comment by mlshvdv** [comment]
@DarkTraveler по наблюдениям задержка есть и в ЛК, и в Open API, так как внутреннее API для моб. приложения и терминала разграничен от Open API — в последнем данные по тем же операциям могут сильно запаздывать, хотя в моб. приложении они уже отображаются. Ну и профит пересчитывается тоже с задержкой.
