### ISSUE TITLE
Ошибка при установке пакета

### ISSUE THREAD

**Issue by proairat** [TinkoffCreditSystems/invest-openapi-js-sdk#85]
При попытке установки пакета посредством команды npm i @tinkoff/invest-openapi-js-sdk --save выводятся следующие ошибки в консоли:

![image](https://user-images.githubusercontent.com/48524499/89519890-831f1380-d7f6-11ea-9b29-0ecb0164cec2.png)

**Comment by grtsvetkov** [comment]
Та же проблема...

**Comment by ZigGreen** [comment]
Кажется у npm какие-то проблемы.

**Comment by Raptor5** [comment]
Так же глючит

**Comment by Raptor5** [comment]
Кто подскажет, в какой IDE пример компилировать лучше? Или тут просто tsc index.ts?

**Comment by ZigGreen** [comment]
Да, проблема на npm (https://status.npmjs.org/). Следите за обновлением статуса.

**Comment by ZigGreen** [comment]
Проблема уже решилась.
