### ISSUE TITLE
Ошибка при отмене ордера

### ISSUE THREAD

**Issue by tamazyanarsen** [TinkoffCreditSystems/invest-openapi-js-sdk#9]
Использую пример с git
![image](https://user-images.githubusercontent.com/25464296/69932172-102d0280-14db-11ea-9a0a-1836184a7877.png)
При вызове cancelOrder выдает ошибку 
![image](https://user-images.githubusercontent.com/25464296/69932193-2a66e080-14db-11ea-9aff-0369d4a87deb.png)

**Comment by NikitaMelnikov** [comment]
Добрый день, в Sandbox заявки исполняются мгновенно, соответственно отменить исполненную сделку невозможно

**Comment by tamazyanarsen** [comment]
понял, спасибо
