### ISSUE TITLE
Не могу запустить example

### ISSUE THREAD

**Issue by co-o-ox** [TinkoffCreditSystems/invest-openapi-js-sdk#90]
Не могу запустить example. 
Выдает вот такую ошибку.
MacBook-Pro-Maksim:untitled4 m$ tsc app.ts
error TS2468: Cannot find global value 'Promise'.

app.ts:8:18 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

8 !(async function run() {
                   ~~~


Found 2 errors.

Подскажите,  что делать? 
Может я что-то не так делаю?

**Comment by ZigGreen** [comment]
что выводит `node -v`?

**Comment by co-o-ox** [comment]
> что выводит `node -v`?

MacBook-Pro-Maksim:example maksimsavcenko$ node -v
v14.9.0

**Comment by co-o-ox** [comment]
> что выводит `node -v`?

 Добавил в tsconfig.json строку 
    "lib": ["es2015"],
Теперь вот такая ошибка:
MacBook-Pro-Maksim:example maksimsavcenko$ tsc index.ts
error TS2468: Cannot find global value 'Promise'.


Found 1 error.

**Comment by ZigGreen** [comment]
tsconfig.json как сейчас выглядит?

**Comment by co-o-ox** [comment]
> tsconfig.json как сейчас выглядит?

{
  "compilerOptions": {
    "declaration": true,
    "declarationDir": "./build",
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "strict": true,
    "module": "commonjs",
    "lib": ["es2015",
            "es2016"
            ],
    "target": "es5",
    "moduleResolution": "node",
    "noUnusedParameters": true,
    "esModuleInterop": true
  }

**Comment by co-o-ox** [comment]
Если вот так пишу  
MacBook-Pro-Maksim:example maksimsavcenko$ t**sc index.ts --lib ES2015**
index.ts:14:3 - error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.

14   console.log(await api.setCurrenciesBalance({ currency: 'USD', balance: 1000 })); // 1000$ на счет

То ругается на все упоминания **console**

**Comment by ZigGreen** [comment]
tsc какой версии?

**Comment by co-o-ox** [comment]
> tsc какой версии?

Сегодня устанавливал. 
typescript@4.0.2 пишет в терминале, в web shtorm пишет 3.9.5

**Comment by ZigGreen** [comment]
а пример из папки example запускается?

**Comment by co-o-ox** [comment]
> а пример из папки example запускается?

 Я его и пытаюсь запустить

**Comment by ZigGreen** [comment]
Чтобы запустить пример нужно: 
1. cклонировать репозиторий 
2. сделать: `cd example`
3. `npm i`
4. `npm start`

**Comment by co-o-ox** [comment]
> Чтобы запустить пример нужно:
> 
> 1. cклонировать репозиторий
> 2. сделать: `cd example`
> 3. `npm i`
> 4. `npm start`

ЧТо я не так делаю? 
1. Скачанный архив из гет хаб распаковал заново
2. зашел через консоль в  example 
3. в   index.ts прописал свои токены
4. npm i , npm start
5. опять ошибка 
npm i
MacBook-Pro-Maksim:example maksimsavcenko$ npm start

> example@1.0.0 start /Users/maksimsavcenko/Downloads/App/ApiJS/invest-openapi-js-sdk-master-2/example
> ts-node index.ts


/Users/maksimsavcenko/Downloads/App/ApiJS/invest-openapi-js-sdk-master-2/example/node_modules/ts-node/src/index.ts:421
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:9:18 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

9 !(async function run() {
                   ~~~

    at createTSError (/Users/maksimsavcenko/Downloads/App/ApiJS/invest-openapi-js-sdk-master-2/example/node_modules/ts-node/src/index.ts:421:12)
    at reportTSError (/Users/maksimsavcenko/Downloads/App/ApiJS/invest-openapi-js-sdk-master-2/example/node_modules/ts-node/src/index.ts:425:19)
    at getOutput (/Users/maksimsavcenko/Downloads/App/ApiJS/invest-openapi-js-sdk-master-2/example/node_modules/ts-node/src/index.ts:553:36)
    at Object.compile (/Users/maksimsavcenko/Downloads/App/ApiJS/invest-openapi-js-sdk-master-2/example/node_modules/ts-node/src/index.ts:758:32)
    at Module.m._compile (/Users/maksimsavcenko/Downloads/App/ApiJS/invest-openapi-js-sdk-master-2/example/node_modules/ts-node/src/index.ts:837:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/maksimsavcenko/Downloads/App/ApiJS/invest-openapi-js-sdk-master-2/example/node_modules/ts-node/src/index.ts:840:12)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@1.0.0 start: `ts-node index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the example@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maksimsavcenko/.npm/_logs/2020-09-04T12_33_41_899Z-debug.log

**Comment by co-o-ox** [comment]
> Чтобы запустить пример нужно:
> 
> 1. cклонировать репозиторий
> 2. сделать: `cd example`
> 3. `npm i`
> 4. `npm start`

Прописал 
    "lib": ["dom","es2015"],
и все заработало!
УРА! 
Спасибо тебе за помощь!
