### ISSUE TITLE
Неправильный экспорт

### ISSUE THREAD

**Issue by Riim** [TinkoffCreditSystems/invest-openapi-js-sdk#91]
В d.ts написано `export default class OpenAPI`, по факту же свойство default в собранном файле не проставляется.
Из-за этого приходится вместо
```js
import OpenAPI from '@tinkoff/invest-openapi-js-sdk';
new OpenAPI(...);
```
писать так
```js
import OpenAPI_ from '@tinkoff/invest-openapi-js-sdk';
import OpenAPI = require('@tinkoff/invest-openapi-js-sdk');
new ((OpenAPI as any) as typeof OpenAPI_)(...);
```

**Comment by ZigGreen** [comment]
А какая ошибка возникает? в example тоже такое поведение?

**Comment by Riim** [comment]
TypeError: invest_openapi_js_sdk_1.default is not a constructor

Скорей всего вы не видите эту ошибку из-за включённой опции esModuleInterop в проекте где используется библиотека. Опция эта по сути костыль для старых неподдерживаемых библиотек. Современные же библиотеки по-хорошему должны работать без неё. Webpack здесь всё правильно собирает, а вот rollup подкладывает такую свинью. Помнится я мучился с этим вот в этой https://github.com/Riim/omyumyum библиотечке, сначала пытался rollup правильно настроить, но в конечном счёте всё вроде бы решилось вот этими строками: https://github.com/Riim/omyumyum/blob/1bc2aae16eb81fe361760af7f9945ab8fe2cf675/src/OmYumYum.ts#L50-L51 . То есть экспорт происходит и default и обычный. В таком варианте rollup начал выдавать нужный результат: https://github.com/Riim/omyumyum/blob/1bc2aae16eb81fe361760af7f9945ab8fe2cf675/dist/OmYumYum.umd.js#L521-L522 .

**Comment by Riim** [comment]
Ну и вообще default не очень хорошая штука: https://habr.com/ru/post/337578/#comment_10409156 .

**Comment by ZigGreen** [comment]
Если добавить недефольный экспорт. Поможет решить проблему? Если да, то закинь пожалуйста пр.

**Comment by dmitryshelomanov** [comment]
был пр или нет ? Все работает
Это уже проблемы твоего сборщика
Дефолтный экспорт стоит
Для библиотечного кода это не критично
Яркий пример ```import React from 'react'```

**Comment by Riim** [comment]
> Это уже проблемы твоего сборщика

тут скорее проблема как раз вашего сборщика, который `export default class OpenAPI` превращает в `module.exports = OpenAPI` вместо положенного `exports.default = OpenAPI`. Сборщик я не использую, просто пропускаю через typescript-компилятор, который вот этот код:
```js
import OpenAPI from '@tinkoff/invest-openapi-js-sdk';
console.log(OpenAPI);
```
превращает в такой:
```js
const invest_openapi_js_sdk_1 = require("@tinkoff/invest-openapi-js-sdk");
console.log(invest_openapi_js_sdk_1.default);
```
то есть в результирующем коде есть `.default` который typescript ставит видя его в .d.ts файле, но которого нет в скомпилированном коде вашей библиотеки.

@dmitryshelomanov, ты попробуй всё же разобраться в проблеме, а не с ходу кричать "проблема на вашей стороне".

> был пр или нет ?

у меня не было проблем с этим, я знаю как это обходить, тк. не первый раз сталкиваюсь, так что мне эти изменения не нужны, но я подумал они могут пригодиться вашим пользователям. Если уверены, что они с этим не столкнутся (ну или вам плевать на них), закройте ишъю и забейте.

**Comment by dmitryshelomanov** [comment]
ты же сам написал что ролап не может
это твоя уже проблема

**Comment by ZigGreen** [comment]
@Riim а можно ваш tsconfig?

**Comment by Riim** [comment]
> ты же сам написал что ролап не может

Я не использую сборщик, здесь разговор про вашу сборку на rollup.

> это твоя уже проблема

Да угомонись ты уже. Ты же явно не понимаешь о какой проблеме сейчас речь. Так зачем лезешь если не готов разбираться?


@ZigGreen
> модульную систему node

Посмотрел как реализовали нативные импорты в node, похоже там действительно default никак не используется, несмотря на описание default в стандарте языка. Видимо так сделали для совместимости со старым кодом и если брать поведение ноды как источник истины, то, в общем-то, всё правильно rollup собирает. Ну а typescript уже пытается подстраиваться под эту особенность с помощью опции.

> esModuleInterop -- как раз для описанной выше проблемы

Была у меня давно какая-то неприятная проблема с esModuleInterop, с тех пор стараюсь избегать её использования, но, видимо, стоит ещё раз попробовать. Спасибо.

**Comment by zartdinov** [comment]
Да, получаю тоже самое:

`TypeError: invest_openapi_js_sdk_1.default is not a constructor`

Свои и  остальные либы без всяких флагов нормально работают.

Ладно, ничего страшного, все равно собирался сам написать пару запросов.

**Comment by Gordondalos** [comment]
проблема как была так и осталась, нифига не работает

**Comment by maksim-zakharov** [comment]
Решил так:

import * as api from '@tinkoff/invest-openapi-js-sdk';

// @ts-ignore
this.api = new api({ apiURL, secretToken, socketURL });
