### ISSUE TITLE
candle stream api теряет время ответа сервера

### ISSUE THREAD

**Issue by ColCh** [TinkoffCreditSystems/invest-openapi-js-sdk#95]
серверное событие

```
{
    "event": "candle",
    "time": "2019-08-07T15:35:00.029721253Z",
    "payload": {
        "o": 64.0575,
        "c": 64.0575,
        "h": 64.0575,
        "l": 64.0575,
        "v": 156,
        "time": "2019-08-07T15:35:00Z",
        "interval": "5min",
        "figi": "BBG0013HGFT4"
    }
}
```

а что получаем мы в коллбеке 

```
  {
    o: 75.2525,
    c: 75.2475,
    h: 75.2525,
    l: 75.2475,
    v: 721,
    time: '2020-09-17T18:02:00Z',
    interval: '1min',
    figi: 'BBG0013HGFT4'
  }
```

я хочу получить "time".

причина кроется тут

![image](https://user-images.githubusercontent.com/599439/93510230-8941fd00-f929-11ea-9099-7cdaecf7ed8d.png)

то есть, поле time даже не достаём

в исходничках это тут https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/c1159729f9016dbfa473c0142893d05ec260b768/src/Streaming.ts#L136

**Comment by ZigGreen** [comment]
Привет. Спасибо за разбор проблемы. Можешь сделать пр?

**Comment by ColCh** [comment]
угу, сделаю :)

**Comment by ZigGreen** [comment]
еще актуально?

**Comment by ColCh** [comment]
Да. У нас перформанс ревью было на работе, некогда было :)
