### ISSUE TITLE
Ошибка при запросе .orders() .cancelOrder()

### ISSUE THREAD

**Issue by penoplaster83** [TinkoffCreditSystems/invest-openapi-js-sdk#96]
В начале прошлой недели всё работало корректно. Сейчас же некоторые запросы к апи не робят, в частности **.orders()** и **cancelOrder()**. Сегодня прям кошмар. Просто не возвращаются ордера в 99% случаев. В коде ничего не менял, да и в этом запросе в общем-то закосячить негде.

**Такую вот ошибку мне try catch отдает:**
FetchError: invalid json response body at https://api-invest.tinkoff.ru/openapi/orders reason: **Unexpected end of JSON input**
    at C:\Users\User\Desktop\TINKA\example\node_modules\node-fetch\lib\body.js:48:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at OpenAPI.makeRequest (C:\Users\User\Desktop\TINKA\example\node_modules\@tinkoff\invest-openapi-js-sdk\build\OpenAPI.cjs.js:249:19) {
  type: 'invalid-json'
}

Скажите, это баг, временный перегруз на сервере или проблема на моей стороне?

Пакеты:
![image](https://user-images.githubusercontent.com/42916143/94413310-9493f480-0183-11eb-9c3f-3f29a5b110e2.png)

**Comment by penoplaster83** [comment]
Блок где запрашиваются ордера. Пребывает без изменений уже месяц или 2. Но проблемы лишь недавно начались.
![image](https://user-images.githubusercontent.com/42916143/94414129-a4600880-0184-11eb-9e3d-acde60e4039c.png)

**Comment by co-o-ox** [comment]
Та же проблема уже полторы недели. И решения ее пока не нашел

**Comment by penoplaster83** [comment]
В дополнение: мелькнула ошибка с тем же заголовком возникла и при создании ордера (Unexpected end of JSON input)
В отличии от кейса с запросом списка ордеров, где данной ошибкой заканчивается большая часть попыток в последние несколько дней, при создании ордера она выпадает крайне редко. Один раз по сути заметил. Ранее вовсе не замечал

(node:3080) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://api-invest.tinkoff.ru/openapi/orders/limit-order?figi=BBG000BJBXZ2 reason: Unexpected end of JSON input
    at C:\Users\User\Desktop\TINKA\example\node_modules\node-fetch\lib\body.js:48:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at OpenAPI.makeRequest (C:\Users\User\Desktop\TINKA\example\node_modules\@tinkoff\invest-openapi-js-sdk\build\OpenAPI.cjs.js:249:19)
(node:3080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6296)

**Comment by penoplaster83** [comment]
> Та же проблема уже полторы недели. И решения ее пока не нашел

это грустно =(
робот простаивает по сути

**Comment by ZigGreen** [comment]
тут идет обсуждение 
duplicates: https://github.com/TinkoffCreditSystems/invest-openapi/issues/359
