### ISSUE TITLE
Как создать отложенную заявку? Stop Loss/Teik Profit

### ISSUE THREAD

**Issue by DarkTraveler** [TinkoffCreditSystems/invest-openapi-js-sdk#98]
Добрый день, как верно после покупки инструмента, либо продажи, выставить Stop Loss/Teik Profit?

**Comment by ZigGreen** [comment]
День добрый! на данный момент такой функциональности в OpenApi нет. Можно сделать только через web-терминал, мобильное приложение или web версию.

**Comment by DarkTraveler** [comment]
@ZigGreen подскажете, нету в планах?

**Comment by ZigGreen** [comment]
такие вопросы лучше задать в https://github.com/TinkoffCreditSystems/invest-openapi
Этот репозиторий чисто для JavaScript клиента.
