### ISSUE TITLE
Повторная покупка

### ISSUE THREAD

**Issue by polkila** [TinkoffCreditSystems/invest-openapi-js-sdk#99]
https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/7e60e1a7843d8b7c68573b47ed2c7a7baef911f3/example/index.ts#L18

api.instrumentPortfolio({ figi }) не стоит использовать для проверки исполнения ордера. Тк если бумага уже присутствует в портфеле, и если совершать повторную покупку, instrumentPortfolio покажет положительный результат, не зависимо от того, как исполнился/не исполнился ордер.

У себя я сделал следующим образом, обращение к "/orders/limit-order" возвращает executedLots и orderId.
Если executedLots меньше запрошенных lots, тогда запоминаем orderId для опроса "/orders" и поиска заявки.

Вообще, хотелось бы, чтобы в OpenAPI была возможность зарегистрировать webhook, на который приходили бы уведомления о завершённых сделках, или получать уведомления по каналу в WebSocket. Вместо того, чтобы опрашивать "/orders" по интервалу.

**Comment by ZigGreen** [comment]
Это же просто пример. Специально максимально просто написано. 

> Вообще, хотелось бы, чтобы в OpenAPI была возможность зарегистрировать webhook, на который приходили бы уведомления о завершённых сделках, или получать уведомления по каналу в WebSocket. Вместо того, чтобы опрашивать "/orders" по интервалу.

Фича-реквесты можно вот сюда https://github.com/TinkoffCreditSystems/invest-openapi/issues
